name: MMOItemTrade
version: '1.0.0'
main: com.binggre.mmoitemshop.MMOItemTrade
api-version: '1.20'
authors: [ binggre ]
depend: ['MMOPlayerData', 'MMOUpdater']
commands:
  교환:
    permission: mmoitemtrade.admin